import { initializeApp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";
import { getFirestore, collection, addDoc, doc, updateDoc, deleteDoc, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyD8K11TQkjsNZnQVc7IoAjrpiTVE_8QAjk",authDomain:"sistema-de-ventas-euro-moda.firebaseapp.com",projectId:"sistema-de-ventas-euro-moda",storageBucket:"sistema-de-ventas-euro-moda.firebasestorage.app",messagingSenderId:"731115391311",appId:"1:731115391311:web:400fbb7f44ab1c18ad5d3a"};
const app=initializeApp(firebaseConfig),db=getFirestore(app);
let productos=[],ventas=[],gastos=[],carrito=[];
const gastosIniciales=[{nombre:"Alquiler",monto:1500},{nombre:"Luz",monto:50},{nombre:"Seguridad",monto:60},{nombre:"Internet",monto:35},{nombre:"Bolsas",monto:20},{nombre:"Publicidad redes sociales",monto:200},{nombre:"Otros",monto:5}];

estadoBase.textContent="Firebase conectado";
onSnapshot(collection(db,"productos"),s=>{productos=s.docs.map(d=>({id:d.id,...d.data()}));actualizarTodo();},e=>{estadoBase.textContent="Error: revisa reglas";console.error(e)});
onSnapshot(collection(db,"ventas"),s=>{ventas=s.docs.map(d=>({id:d.id,...d.data()}));actualizarTodo();});
onSnapshot(collection(db,"gastos"),async s=>{gastos=s.docs.map(d=>({id:d.id,...d.data()}));if(gastos.length===0){for(const g of gastosIniciales)await addDoc(collection(db,"gastos"),g)}actualizarTodo();});

const dinero=n=>(Number(n)||0).toFixed(2)+" Bs";
const hoyISO=()=>new Date().toISOString().slice(0,10);
const mesActual=()=>new Date().toISOString().slice(0,7);

window.mostrarSeccion=(id,boton)=>{document.querySelectorAll(".seccion").forEach(s=>s.classList.remove("visible"));document.getElementById(id).classList.add("visible");document.querySelectorAll(".menu button").forEach(b=>b.classList.remove("activo"));if(boton)boton.classList.add("activo");actualizarTodo();}

async function convertirImagen(archivo){if(!archivo)return"";return new Promise(r=>{const l=new FileReader();l.onload=e=>{const im=new Image();im.onload=()=>{const c=document.createElement("canvas"),m=600;let w=im.width,h=im.height;if(w>h&&w>m){h=h*m/w;w=m}if(h>=w&&h>m){w=w*m/h;h=m}c.width=w;c.height=h;c.getContext("2d").drawImage(im,0,0,w,h);r(c.toDataURL("image/jpeg",.7))};im.src=e.target.result};l.readAsDataURL(archivo)})}

formProducto.addEventListener("submit",async e=>{e.preventDefault();await addDoc(collection(db,"productos"),{codigo:codigo.value.trim().toUpperCase(),nombre:nombre.value.trim().toUpperCase(),categoria:categoria.value.trim().toUpperCase(),genero:genero.value,talla:talla.value.trim().toUpperCase(),color:color.value.trim().toUpperCase(),cantidad:Number(cantidad.value),costo:Number(costo.value),precio:Number(precio.value),proveedor:proveedor.value.trim(),descripcion:descripcion.value.trim(),imagen:await convertirImagen(imagen.files[0]),fechaIngreso:hoyISO(),creado:serverTimestamp()});alert("Producto guardado");limpiarProducto();});
window.limpiarProducto=()=>formProducto.reset();

function grupos(){const m={};productos.forEach(p=>{const c=(p.codigo||"SIN CODIGO").toUpperCase();(m[c]=m[c]||[]).push(p)});return m}
function estado(c){if(c<=0)return["Agotado","estado-agotado"];if(c<=2)return["Stock bajo","estado-bajo"];return["Disponible","estado-ok"]}

window.renderizarInventarioAgrupado=()=>{const q=(buscarInventario.value||"").toLowerCase();inventarioAgrupado.innerHTML="";Object.entries(grupos()).filter(([cod,arr])=>(cod+arr[0].nombre).toLowerCase().includes(q)).sort().forEach(([cod,arr])=>{const total=arr.reduce((s,p)=>s+Number(p.cantidad),0),img=arr.find(p=>p.imagen)?.imagen||"",p0=arr[0];let filas="";arr.sort((a,b)=>(a.color+a.talla).localeCompare(b.color+b.talla)).forEach(p=>{const[txt,cls]=estado(Number(p.cantidad));filas+=`<tr><td>${p.talla}</td><td>${p.color}</td><td>${p.cantidad}</td><td>${dinero(p.costo)}</td><td>${dinero(p.precio)}</td><td class="${cls}">${txt}</td><td><button class="accion secundario" onclick="sumarStock('${p.id}')">+ Stock</button><button class="accion" onclick="eliminarProducto('${p.id}')">Eliminar</button></td></tr>`});inventarioAgrupado.innerHTML+=`<div class="grupo-codigo"><div class="cabecera-grupo"><div>${img?`<img src="${img}">`:""}<h2>${cod} - ${p0.nombre}</h2><div class="resumen-grupo"><span>Categoría: ${p0.categoria}</span><span>Género: ${p0.genero}</span><span>Total unidades: <b>${total}</b></span><span>Variantes: ${arr.length}</span></div></div><button onclick="abrirEditarCodigo('${cod}')">Editar código completo</button></div><div class="tabla-contenedor"><table><thead><tr><th>Talla</th><th>Color</th><th>Cantidad</th><th>Costo</th><th>Precio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${filas}</tbody></table></div></div>`})}

window.sumarStock=async id=>{const n=Number(prompt("¿Cuántas unidades agregar?")||0);if(n>0){const p=productos.find(x=>x.id===id);await updateDoc(doc(db,"productos",id),{cantidad:Number(p.cantidad)+n})}}
window.eliminarProducto=async id=>{if(confirm("¿Eliminar esta talla/color?"))await deleteDoc(doc(db,"productos",id))}

window.abrirEditarCodigo=cod=>{const arr=productos.filter(p=>p.codigo===cod),p0=arr[0];editCodigo.value=p0.codigo;editNombre.value=p0.nombre;editCategoria.value=p0.categoria;editGenero.value=p0.genero;editCosto.value=p0.costo;editPrecio.value=p0.precio;editProveedor.value=p0.proveedor||"";editDescripcion.value=p0.descripcion||"";matricesEditar.innerHTML="";arr.forEach(p=>{matricesEditar.innerHTML+=`<div class="matriz-fila" data-id="${p.id}"><input class="mTalla" value="${p.talla}" placeholder="Talla"><input class="mColor" value="${p.color}" placeholder="Color"><input class="mCantidad" type="number" value="${p.cantidad}" placeholder="Cantidad"><button onclick="eliminarProducto('${p.id}')">Eliminar</button></div>`});modalEditarCodigo.classList.remove("oculto");}
window.cerrarModal=()=>modalEditarCodigo.classList.add("oculto");
window.guardarEdicionCodigo=async()=>{const filas=[...document.querySelectorAll(".matriz-fila")];for(const f of filas){await updateDoc(doc(db,"productos",f.dataset.id),{codigo:editCodigo.value.trim().toUpperCase(),nombre:editNombre.value.trim().toUpperCase(),categoria:editCategoria.value.trim().toUpperCase(),genero:editGenero.value,costo:Number(editCosto.value),precio:Number(editPrecio.value),proveedor:editProveedor.value.trim(),descripcion:editDescripcion.value.trim(),talla:f.querySelector(".mTalla").value.trim().toUpperCase(),color:f.querySelector(".mColor").value.trim().toUpperCase(),cantidad:Number(f.querySelector(".mCantidad").value)})}alert("Código actualizado completo");cerrarModal();}

window.filtrarProductosVenta=()=>llenarProductosVenta();
function llenarProductosVenta(){const q=(buscarVentaCodigo?.value||"").toLowerCase();productoVenta.innerHTML="";productos.filter(p=>Number(p.cantidad)>0&&(p.codigo+p.nombre+p.talla+p.color).toLowerCase().includes(q)).forEach(p=>{productoVenta.innerHTML+=`<option value="${p.id}">${p.codigo} - ${p.nombre} / ${p.talla} / ${p.color} / Stock: ${p.cantidad} / ${dinero(p.precio)}</option>`});mostrarDetalleVenta()}
productoVenta.addEventListener("change",mostrarDetalleVenta);
function mostrarDetalleVenta(){const p=productos.find(x=>x.id===productoVenta.value);detalleProductoVenta.innerHTML=p?`<h3>${p.codigo} - ${p.nombre}</h3><p>Talla: ${p.talla} · Color: ${p.color} · Precio sugerido: ${dinero(p.precio)} · Stock: ${p.cantidad}</p>${p.imagen?`<img class="mini-img" src="${p.imagen}">`:""}`:"No hay productos disponibles.";if(p)precioVentaManual.value=p.precio||0}

window.agregarAlCarrito=()=>{const p=productos.find(x=>x.id===productoVenta.value);if(!p)return alert("Selecciona un producto");const cant=Number(cantidadVenta.value),precio=Number(precioVentaManual.value);if(cant<=0||precio<0)return alert("Cantidad o precio inválido");const ya=carrito.filter(x=>x.productoId===p.id).reduce((s,x)=>s+x.cantidad,0);if(ya+cant>Number(p.cantidad))return alert("No hay stock suficiente");carrito.push({productoId:p.id,codigo:p.codigo,nombre:p.nombre,talla:p.talla,color:p.color,cantidad:cant,precio,costo:Number(p.costo),subtotal:cant*precio});cantidadVenta.value=1;precioVentaManual.value="";renderizarCarrito();}
function renderizarCarrito(){tablaCarrito.innerHTML="";carrito.forEach((x,i)=>tablaCarrito.innerHTML+=`<tr><td>${x.codigo} - ${x.nombre}</td><td>${x.talla}</td><td>${x.color}</td><td>${x.cantidad}</td><td>${dinero(x.precio)}</td><td>${dinero(x.subtotal)}</td><td><button onclick="quitarCarrito(${i})">Quitar</button></td></tr>`);calcularCambio();}
window.quitarCarrito=i=>{carrito.splice(i,1);renderizarCarrito()}
window.calcularCambio=()=>{const total=carrito.reduce((s,x)=>s+x.subtotal,0),pagado=Number(montoPagado.value)||0;totalCarrito.textContent=dinero(total);cambioVenta.textContent=dinero(Math.max(0,pagado-total));}

window.finalizarVenta=async()=>{if(carrito.length===0)return alert("Agrega productos");const total=carrito.reduce((s,x)=>s+x.subtotal,0),pagado=Number(montoPagado.value)||0;if(metodoPago.value==="Efectivo"&&pagado<total)return alert("El monto pagado es menor al total");for(const x of carrito){const p=productos.find(p=>p.id===x.productoId);if(!p||Number(p.cantidad)<x.cantidad)return alert("Stock insuficiente en "+x.nombre)}const costo=carrito.reduce((s,x)=>s+x.costo*x.cantidad,0);await addDoc(collection(db,"ventas"),{items:carrito,total,pagado,cambio:Math.max(0,pagado-total),costo,ganancia:total-costo,metodo:metodoPago.value,cliente:clienteVenta.value,fecha:new Date().toISOString(),creado:serverTimestamp()});for(const x of carrito){const p=productos.find(p=>p.id===x.productoId);await updateDoc(doc(db,"productos",x.productoId),{cantidad:Number(p.cantidad)-x.cantidad})}alert("Venta registrada");carrito=[];montoPagado.value="";clienteVenta.value="";renderizarCarrito();}

function renderizarVentas(){tablaVentas.innerHTML="";[...ventas].sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha))).forEach(v=>{const det=(v.items||[]).map(i=>`${i.codigo} ${i.nombre} ${i.talla}/${i.color} x${i.cantidad}`).join("<br>")||`${v.codigo||""} ${v.nombre||""}`;tablaVentas.innerHTML+=`<tr><td>${new Date(v.fecha).toLocaleString("es-BO")}</td><td>${det}</td><td>${dinero(v.total)}</td><td>${dinero(v.pagado||v.total)}</td><td>${dinero(v.cambio||0)}</td><td>${v.metodo}</td><td>${dinero(v.ganancia)}</td></tr>`})}
function renderizarStockBajo(){const bajos=productos.filter(p=>Number(p.cantidad)<=2);listaStockBajo.innerHTML=bajos.length?"":"<p>No hay productos por agotarse.</p>";bajos.forEach(p=>listaStockBajo.innerHTML+=`<div class="producto-card">${p.imagen?`<img src="${p.imagen}">`:""}<h3>${p.codigo} - ${p.nombre}</h3><p>${p.talla} · ${p.color}</p><strong>Stock: ${p.cantidad}</strong></div>`)}
function renderizarMasVendidos(){const mapa={};ventas.filter(v=>String(v.fecha).slice(0,7)===mesActual()).forEach(v=>(v.items||[]).forEach(i=>{const k=`${i.codigo} - ${i.nombre} / ${i.talla} / ${i.color}`;mapa[k]=(mapa[k]||0)+Number(i.cantidad)}));const arr=Object.entries(mapa).sort((a,b)=>b[1]-a[1]);listaMasVendidos.innerHTML=arr.length?"":"<p>Aún no hay ventas este mes.</p>";arr.forEach((r,i)=>listaMasVendidos.innerHTML+=`<div class="fila-ranking"><strong>${i+1}. ${r[0]}</strong><span>${r[1]} unidades</span></div>`)}

formGasto.addEventListener("submit",async e=>{e.preventDefault();if(nombreGasto.value&&montoGasto.value){await addDoc(collection(db,"gastos"),{nombre:nombreGasto.value,monto:Number(montoGasto.value)});e.target.reset()}});
function renderizarGastos(){listaGastos.innerHTML=gastos.map(g=>`<p><strong>${g.nombre}:</strong> ${dinero(g.monto)} <button class="accion" onclick="eliminarGasto('${g.id}')">Eliminar</button></p>`).join("");totalGastos.textContent=dinero(gastos.reduce((s,g)=>s+Number(g.monto),0))}
window.eliminarGasto=async id=>await deleteDoc(doc(db,"gastos",id))

function actualizarInicio(){const hoy=hoyISO(),mes=mesActual(),vHoy=ventas.filter(v=>String(v.fecha).slice(0,10)===hoy),vMes=ventas.filter(v=>String(v.fecha).slice(0,7)===mes),totalMes=vMes.reduce((s,v)=>s+Number(v.total),0),costoMes=vMes.reduce((s,v)=>s+Number(v.costo),0),gasto=gastos.reduce((s,g)=>s+Number(g.monto),0);ventasHoy.textContent=dinero(vHoy.reduce((s,v)=>s+Number(v.total),0));ventasMes.textContent=dinero(totalMes);gananciaNeta.textContent=dinero(totalMes-costoMes-gasto);totalPrendas.textContent=productos.reduce((s,p)=>s+Number(p.cantidad),0);cantidadStockBajo.textContent=productos.filter(p=>Number(p.cantidad)<=2).length;reporteVendido.textContent=dinero(totalMes);reporteCosto.textContent=dinero(costoMes);reporteGastos.textContent=dinero(gasto);reporteGanancia.textContent=dinero(totalMes-costoMes-gasto);productoTop.textContent="Ver más vendidos"}
window.descargarVentas=()=>{const filas=["Fecha,Detalle,Total,Pagado,Cambio,Metodo,Ganancia"];ventas.forEach(v=>filas.push(`${v.fecha},"${(v.items||[]).map(i=>i.codigo+" "+i.nombre+" "+i.talla+"/"+i.color+" x"+i.cantidad).join(" | ")}",${v.total},${v.pagado||v.total},${v.cambio||0},${v.metodo},${v.ganancia}`));const blob=new Blob([filas.join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="ventas-euro-moda.csv";a.click()}
function actualizarTodo(){renderizarInventarioAgrupado();llenarProductosVenta();renderizarVentas();renderizarStockBajo();renderizarMasVendidos();renderizarGastos();actualizarInicio();renderizarCarrito();}
